### ISSUE TITLE
click for stars

### ISSUE THREAD

**Issue by hadiMh** [DreaminginCodeZH/MaterialRatingBar#56] opened 2019-02-02 13:24 UTC
hi, I had used this rating bar in my project. i am trying to show users the total rate of a post with these rating bar, for example a post rate is 4.5 so the starts are showing this number but while showing this result the user can also click on the rating bar and change the rating, but these are just for showing the result to the user and I don't want the user to be able to click and change this rating bar number. in fact that feature is for the comment section only, where I ask the user to give a rate to the post and I have not implemented that yet. how can i stop the user from clicking and changing the number of rate of a rating bar? Tnx

**Comment by zhanghai** [comment] 2019-02-02 22:38
Duplicate of #34

**Closed as completed by zhanghai** 2019-02-02 22:38 UTC
Labels: duplicate, question
