### ISSUE TITLE
Error inflating MaterialRatingBar on Android 10

### ISSUE THREAD

**Issue by AhmedDroid** [DreaminginCodeZH/MaterialRatingBar#67] opened 2019-12-30 15:18 UTC
We are facing issue with the library on Android 10 on Samsung Galaxy S10 devices with inflating the view here's the log, I have removed package names with XXX:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/xxx}: android.view.InflateException: Binary XML file line #149 in com.xxx.xxx:layout/xxx: Binary XML file line #72 in com.xxx.xxx:layout/xxx: Binary XML file line #72 in com.xxx.xxxlayout/xxx: Error inflating class me.zhanghai.android.materialratingbar.MaterialRatingBar
Location
ActivityThread.java:3447 - android.app.ActivityThread.performLaunchActivity
```

**Comment by zhanghai** [comment] 2019-12-30 18:34
Duplicate of #63.

**Closed as completed by zhanghai** 2019-12-30 18:34 UTC
Labels: bug, duplicate
