### ISSUE TITLE
Crash on Android 10

### ISSUE THREAD

**Issue by Mateeen** [DreaminginCodeZH/MaterialRatingBar#69] opened 2020-01-10 06:16 UTC
Caused by java.lang.NullPointerException: Attempt to read from field 'android.content.res.ColorStateList me.zhanghai.android.materialratingbar.MaterialRatingBar$c.a' on a null object reference
       at me.zhanghai.android.materialratingbar.MaterialRatingBar.getSupportProgressTintList + 1(MaterialRatingBar.java:1)
       at me.zhanghai.android.materialratingbar.MaterialRatingBar.getProgressTintList + 2(MaterialRatingBar.java:2)
       at android.widget.AbsSeekBar.<init> + 245(AbsSeekBar.java:245)
       at android.widget.RatingBar.<init> + 92(RatingBar.java:92)
       at android.widget.RatingBar.<init> + 88(RatingBar.java:88)
       at android.widget.RatingBar.<init> + 124(RatingBar.java:124)
       at me.zhanghai.android.materialratingbar.MaterialRatingBar.<init> + 4(MaterialRatingBar.java:4)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance + 343(Constructor.java:343)
       at android.view.LayoutInflater.createView + 854(LayoutInflater.java:854)
       at android.view.LayoutInflater.createViewFromTag + 1006(LayoutInflater.java:1006)
       at android.view.LayoutInflater.createViewFromTag + 961(LayoutInflater.java:961)
       at android.view.LayoutInflater.rInflate + 1123(LayoutInflater.java:1123)
       at android.view.LayoutInflater.rInflateChildren + 1084(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate + 1126(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren + 1084(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate + 1126(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren + 1084(LayoutInflater.java:1084)
       at android.view.LayoutInflater.rInflate + 1126(LayoutInflater.java:1126)
       at android.view.LayoutInflater.rInflateChildren + 1084(LayoutInflater.java:1084)
       at android.view.LayoutInflater.inflate + 682(LayoutInflater.java:682)
       at android.view.LayoutInflater.inflate + 534(LayoutInflater.java:534)
       at android.view.LayoutInflater.inflate + 481(LayoutInflater.java:481)

**Comment by zhanghai** [comment] 2020-01-10 06:53
Duplicate of #63.

**Closed as completed by zhanghai** 2020-01-10 06:53 UTC
Labels: duplicate
