### ISSUE TITLE
How to set star default fill with backgroud color ? 

### ISSUE THREAD

**Issue by prashant31191** [DreaminginCodeZH/MaterialRatingBar#24] opened 2017-09-25 09:56 UTC
I want to set start background color, not a border it's like this _https://github.com/prashant31191/prashant31191.github.io/blob/master/images/Capture.PNG_

like total "5" star setprogress(3)

3-back color background
2-gray color background.

**Comment by zhanghai** [comment] 2017-09-26 06:36
Duplicate of #7.

**Closed as completed by zhanghai** 2017-09-26 06:36 UTC
Labels: duplicate, question

**Comment by zhanghai** [comment] 2017-09-26 06:39
Ah #7 is in Chinese - basically this library is following the hollow star design, and if you need the fill stars you may try the appcompat one or some other libraries. And I'm thinking of adding this functionality (with tint backport) recently.

**Comment by zhanghai** [comment] 2017-09-26 08:01
Published in https://github.com/DreaminginCodeZH/MaterialRatingBar/releases/tag/v1.1.1 .
